# Generated by Django 4.2.4 on 2023-09-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0002_delete_carro_delete_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro', models.CharField(max_length=100)),
                ('aprovador', models.CharField(default='Antônio Rezende', max_length=100)),
                ('email', models.EmailField(default='antoniorezende@sicoob.com.br', max_length=254)),
                ('solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('email_solicitante', models.EmailField(blank=True, max_length=254, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.CharField(blank=True, max_length=11, null=True)),
                ('aprovado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=100)),
                ('aprovador', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('email_solicitante', models.EmailField(blank=True, max_length=254, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.CharField(blank=True, max_length=11, null=True)),
                ('aprovado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
