# Generated by Django 4.2.4 on 2023-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_imagem', models.CharField(default='Nome de imagem não definido', max_length=100)),
                ('imagens', models.ImageField(default='not-found.png', upload_to='Tv_imagens/carrossel/%Y/%m/%d/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
