# Generated by Django 4.2.4 on 2023-12-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_imagem', models.CharField(default='Imagem', max_length=100)),
                ('imagem', models.ImageField(default='not-found.png', upload_to='Tv_imagens/carrossel/%Y/%m/%d/')),
                ('PA', models.IntegerField(default=0)),
                ('utilizando', models.BooleanField(default=True)),
                ('adicionado_em', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tv_Imagens',
        ),
    ]
