# Generated by Django 4.2.4 on 2023-12-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0003_tv_pa_delete_tv_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_00',
            new_name='imagem_0',
        ),
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_01',
            new_name='imagem_1',
        ),
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_02',
            new_name='imagem_2',
        ),
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_03',
            new_name='imagem_3',
        ),
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_04',
            new_name='imagem_4',
        ),
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_05',
            new_name='imagem_5',
        ),
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_06',
            new_name='imagem_6',
        ),
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_07',
            new_name='imagem_7',
        ),
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_08',
            new_name='imagem_8',
        ),
        migrations.RenameField(
            model_name='tv_pa',
            old_name='imagem_09',
            new_name='imagem_9',
        ),
    ]
