# Generated by Django 4.2.4 on 2023-12-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0004_rename_imagem_00_tv_pa_imagem_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_0',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_1',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_10',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_11',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_12',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_13',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_14',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_15',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_16',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_17',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_18',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_19',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_2',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_20',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_3',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_4',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_5',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_6',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_7',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_8',
        ),
        migrations.RemoveField(
            model_name='tv_pa',
            name='imagem_9',
        ),
        migrations.CreateModel(
            name='Tv_Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_imagem', models.CharField(default='Imagem', max_length=100)),
                ('imagem', models.ImageField(upload_to='Tv_imagens/carrossel/%Y/%m/')),
                ('adicionado_em', models.DateField(auto_now_add=True)),
                ('PA', models.ManyToManyField(to='carrossel.tv_pa')),
            ],
        ),
        migrations.AddField(
            model_name='tv_pa',
            name='images',
            field=models.ManyToManyField(to='carrossel.tv_imagem'),
        ),
    ]
