# Generated by Django 4.2.4 on 2023-12-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0005_remove_tv_pa_imagem_0_remove_tv_pa_imagem_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv_pa',
            name='images',
        ),
        migrations.DeleteModel(
            name='Tv_Imagem',
        ),
    ]
