# Generated by Django 4.2.4 on 2023-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0007_tv_imagem_tv_pa_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv_imagem',
            name='pa',
        ),
        migrations.AlterField(
            model_name='tv_pa',
            name='images',
            field=models.ManyToManyField(null=True, to='carrossel.tv_imagem'),
        ),
    ]
