# Generated by Django 4.2.4 on 2023-12-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrossel', '0008_remove_tv_imagem_pa_alter_tv_pa_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_imagem',
            name='imagem',
            field=models.ImageField(upload_to='Tv_imagens/carrossel/'),
        ),
    ]
